//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMove.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeMove.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ImDema/FreeMove {0}
        ///
        ///This program is licensed under the GNU General Public License v3.0
        ///For more informations https://github.com/imDema/FreeMove/blob/master/LICENSE.txt 
        ///
        ///https://github.com/imDema に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutContent {
            get {
                return ResourceManager.GetString("AboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s strongly recommended not to move the &quot;Program Files&quot; or the &quot;Program Files (x86)&quot; directories as it can lead to unexpexted behaviour.
        ///You are free to move any of the programs contained in those directories without any problem instead.
        ///
        ///Are you sure you want to disable safe mode? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisableSafeModeMessage {
            get {
                return ResourceManager.GetString("DisableSafeModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERROR creating symbolic link.
        ///The folder is in the new position but the link could not be created.
        ///Try running as administrator
        ///
        ///Do you want to move the files back? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnauthorizedLink {
            get {
                return ResourceManager.GetString("ErrorUnauthorizedLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The error was caused by a file which couldn&apos;t be moved, it may be in use or you may not have the required permissions.
        ///
        ///Try running this program as administrator and/or close any program that is using the file specified in the details
        ///
        ///DETAILS: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnauthorizedMoveDetails {
            get {
                return ResourceManager.GetString("ErrorUnauthorizedMoveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: {0}
        ///
        ///How do you want to proceed?
        ///&quot;Abort&quot; to revert changes
        ///&quot;Ignore&quot; to stop the program に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorUnauthorizedMoveMessage {
            get {
                return ResourceManager.GetString("ErrorUnauthorizedMoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not retrieve the version information
        ///from the GitHub server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GitHubErrorMessage {
            get {
                return ResourceManager.GetString("GitHubErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to proceed?
        ///
        ///By ignoring you will leave all the files as they are now: part of the files will already be in the new location and missing from the old one! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IgnoreMessage {
            get {
                return ResourceManager.GetString("IgnoreMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There was an error when moving the files using FreeMove on {0} and you chose to ignore it.
        ///The rest of the contents of this directory can be found at &quot;{1}&quot; unless they were moved.
        ///Next time use &quot;Abort&quot; in case of an error to move the files back or &quot;Retry&quot; to try again.
        ///
        ///If this text file was useful or if you would have preferred it wasn&apos;t created let me know.
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IgnoreTextFile {
            get {
                return ResourceManager.GetString("IgnoreTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ImDema-FreeMove-Updater に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
    }
}
